name: The City
favicon: null
layout_spectrum: 0.19364284072071314
typography_spectrum: 0.32037601131014526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23960193200036883
  lightness: 0.1814720027614385
  saturation: 0.8400617546867579
  rhythmicContrast: 0.4189662814605981
purpose: []
